### ISSUE TITLE
[BUG] (Enemy Team) Purple Enemy Item Drop Issue with Exploding Enemy Ships

### ISSUE THREAD

**Issue by Dream-no24** [dev-jjjjjeong-bin/Invaders-SDP#54]
## Problem Description

Currently, purple enemies are supposed to drop items upon death. However, when they are killed by exploding enemy ships, they do not drop any items.

## Todo List

- [ ] Ensure purple enemies drop items when killed by exploding enemy ships
- [ ] Validate item drop function works on purple enemies regardless of how they die

## Feature Description

Ensure purple enemies drop items in all situations, including when killed by exploding enemy ships.

## Additional Information

Purple enemies that drop items and explosive enemyship are developed by Team Enemy. The interaction between exploding ships and item drops may need additional logic.

**Comment by HSHyun** [comment]
The method for dropping items from magenta mobs works as follows:
1. The collision between the enemy and bullets is detected in the _**manageCollisions_add_item**_ method of the **_GameScreen_** class.
2. If a collision is found, the **__destroy_** function of the **_EnemyShipFormation_** class is executed.
3. Afterward, if the destroyed enemy is **magenta**, an item is dropped in **_manageCollisions_add_item._**

However, enemies that die due to the explosive mob are not killed by the **__destroy_** called from **_manageCollisions_add_item_** but rather by the chain explosion method explosive from the **_EnemyShipFormation_** class. In other words, magenta mobs killed by the explosion method in **_EnemyShipFormation_** didn’t drop items because they were not detected as dead in **_GameScreen._**

To fix this, I modified the code so that instead of dropping an item when a collision occurs, items are dropped when **__destroy_** is called and the magenta mob dies.

**Comment by Dream-no24** [comment]
After testing, I confirmed that when the Magenta enemy is destroyed by an explosive enemy, the item is dropped correctly. 

Excellent work, thank you!

https://github.com/user-attachments/assets/afa43f08-8185-4541-8dd0-54449e8e633f
